replicaCount: 1

image:
  repository: acuvity/acuvity-demo
  pullPolicy: Always
  tag: ""

imagePullSecrets: []

securityContext:
  # capabilities:
  #   drop:
  #     - ALL
  # runAsNonRoot: true
  # runAsUser: 1001

service:
  type: ClusterIP
  port: 3000

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

systemPrompt: "You are an AI assistant helping a software engineer..."

# if host is empty then it will use the name as k8s svc host
# for node port or other pout the host /port instead
mcpServers:
  - name: mcp-server-fetch
    host:
  - name: mcp-server-brave-search
    host:
  - name: mcp-server-github
    host:
  - name: mcp-server-sequential-thinking
    host:
  - name: mcp-server-memory
    host:
  - name: mcp-server-microsoft
    host:

secrets:
  openai_key:
  anthropic_key:
  descope_project_id:

apex: 
  enabled: false