replicaCount: 1

image:
  agent:
    repository: acuvity/acuvity-chatbot-agent
    pullPolicy: Always
    tag: latest
  ui:
    repository: acuvity/acuvity-chatbot-ui
    pullPolicy: Always
    tag: latest
  postgres:
    repository: postgres
    pullPolicy: Always
    tag: 15-alpine
  curl:
    repository: curlimages/curl
    pullPolicy: Always
    tag: latest

imagePullSecrets: []

securityContext:
  # capabilities:
  #   drop:
  #     - ALL
  # runAsNonRoot: true
  # runAsUser: 1001

service:
  ui:
    type: ClusterIP
    port: 3000
  agent:
    type: ClusterIP
    port: 8000

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

# if host is empty then it will use the name as k8s svc host
# for node port or other pout the host /port instead
mcpServers:
  - name: mcp-server-fetch
    host:
  - name: mcp-server-brave-search
    host:
  - name: mcp-server-github
    host:
  - name: mcp-server-sequential-thinking
    host:
  - name: mcp-server-memory
    host:
  - name: mcp-server-microsoft
    host:

agent:
  corsOrigins: '["http://localhost:3000","http://localhost:8000"]'

secrets:
  anthropic_key:
  descope_project_id:

apex: 
  enabled: false
